import type { Data, Base } from "./types";
import { today } from "./calculations";
export function demoData(): Data {
  const base = (id: string): Base => ({
    id,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  });
  const d = today();
  const customers = [
    {
      ...base("demo-c1"),
      company: "Café Morgenrot",
      contact: "Anna Beispiel",
      email: "anna@example.invalid",
      phone: "",
      street: "Friedrichstraße 18",
      zip: "10117",
      city: "Berlin",
      industry: "Café",
      source: "Beispieldaten",
      notes: "Neue Terrasse. Mobiles Terminal und Belegdruck besprechen.",
      lat: 52.507,
      lng: 13.39,
    },
    {
      ...base("demo-c2"),
      company: "Späti am Park",
      contact: "Max Muster",
      email: "max@example.invalid",
      phone: "",
      street: "Görlitzer Straße 24",
      zip: "10997",
      city: "Berlin",
      industry: "Kiosk",
      source: "Beispieldaten",
      notes: "Interesse an Sortimentserweiterung.",
      lat: 52.499,
      lng: 13.436,
    },
    {
      ...base("demo-c3"),
      company: "Studio West",
      contact: "Mia Beispiel",
      email: "mia@example.invalid",
      phone: "",
      street: "Kantstraße 31",
      zip: "10625",
      city: "Berlin",
      industry: "Dienstleistung",
      source: "Beispieldaten",
      notes: "Kostenvergleich vorbereiten.",
      lat: 52.506,
      lng: 13.309,
    },
  ];
  return {
    customers,
    opportunities: [
      {
        ...base("demo-o1"),
        customer_id: "demo-c1",
        division: "sumup",
        stage: "Termin",
        potential: 8500,
        details: {},
      },
      {
        ...base("demo-o2"),
        customer_id: "demo-c2",
        division: "vape",
        stage: "Angebot",
        potential: 1200,
        details: {},
      },
      {
        ...base("demo-o3"),
        customer_id: "demo-c3",
        division: "sumup",
        stage: "Neu",
        potential: 4200,
        details: {},
      },
    ],
    tasks: [
      {
        ...base("demo-t1"),
        customer_id: "demo-c1",
        division: "sumup",
        title: "Kartenzahlungsanalyse besprechen",
        due_at: d + "T09:30:00+02:00",
        done: false,
      },
      {
        ...base("demo-t2"),
        customer_id: "demo-c2",
        division: "vape",
        title: "Sortiment und Abnahmemenge abstimmen",
        due_at: d + "T11:00:00+02:00",
        done: false,
      },
      {
        ...base("demo-t3"),
        customer_id: "demo-c3",
        division: "sumup",
        title: "Erstkontakt vorbereiten",
        due_at: d + "T14:00:00+02:00",
        done: false,
      },
    ],
    suppliers: [
      {
        ...base("demo-s1"),
        name: "Beispiel-Großhandel",
        website: "",
        terms: "Nur Demo, keine echten Händlerpreise.",
        shipping_net: 6.9,
        min_order: 100,
        lead_days: 3,
      },
    ],
    products: [
      {
        ...base("demo-p1"),
        supplier_id: "demo-s1",
        sku: "DEMO-01",
        ean: "",
        name: "Beispielprodukt · Pod-System",
        category: "Pods",
        ek_net: 4.5,
        vk_net: 7.5,
        vat: 19,
        stock: 120,
        pack_size: 10,
        source_date: d,
        source_url: "",
      },
    ],
    offers: [],
    routes: [],
    events: [
      {
        ...base("demo-e1"),
        customer_id: "demo-c1",
        division: "sumup",
        kind: "Notiz",
        description: "Beratungstermin vereinbart.",
      },
    ],
  };
}
