import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
let handler:(req:Request)=>Promise<Response>;
const owner='d61e2d3e-f665-41a9-975e-ea89335ab61a',requestId='11111111-1111-4111-8111-111111111111';
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json'}});
async function call(body:object,token?:string){return handler(new Request('https://example.invalid',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}))}
beforeEach(async()=>{vi.resetModules();vi.stubGlobal('Deno',{env:{get:(k:string)=>k==='SUPABASE_URL'?'https://db.invalid':'server-key'},serve:(f:typeof handler)=>{handler=f}});await import('../supabase/functions/nx-software-sales/index')});
afterEach(()=>vi.unstubAllGlobals());
describe('software owner authorization and invitation lifecycle',()=>{
 it('denies management without a token and never reaches the database',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);expect((await call({action:'list'})).status).toBe(401);expect(fetch).not.toHaveBeenCalled()});
 it('rejects invalid tokens and valid users without an owner grant',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>json({},401)));expect((await call({action:'list'},'bad')).status).toBe(401);vi.stubGlobal('fetch',vi.fn(async(input)=>String(input).endsWith('/auth/v1/user')?json({id:owner}):json([])));expect((await call({action:'list'},'not-owner')).status).toBe(403)});
 it('creates an expiring invitation storing only the code hash and permits revocation',async()=>{let inserted:Record<string,unknown>|undefined;vi.stubGlobal('fetch',vi.fn(async(input,init)=>{const u=String(input);if(u.endsWith('/auth/v1/user'))return json({id:owner});if(u.includes('nx_owner?'))return json([{user_id:owner}]);if(u.includes('nx_software_requests?'))return json([{id:requestId,company:'Test GmbH',contact:'Test'}]);if(u.includes('nx_demo_invitations')&&init?.method==='POST'){inserted=JSON.parse(String(init.body));return json([{...inserted,id:requestId,created_at:new Date().toISOString()}])}if(u.includes('nx_demo_invitations')&&init?.method==='PATCH')return json([{id:requestId}]);throw Error(u)}));const r=await call({action:'invite',request_id:requestId,days:7},'owner');expect(r.status).toBe(200);const data=await r.json();expect(data.code).toMatch(/^NX[A-F0-9]{32}$/);expect(inserted).not.toHaveProperty('code');expect(inserted?.code_hash).toMatch(/^[a-f0-9]{64}$/);expect(Date.parse(data.invitation.expires_at)-Date.now()).toBeGreaterThan(6.9*86400000);expect((await call({action:'revoke',id:requestId},'owner')).status).toBe(200);expect((await call({action:'invite',request_id:requestId,days:365},'owner')).status).toBe(400)});
});
