export const demoLink='https://www.nexaro-solutions.de/produktrundgang/';
export type Language='de'|'en';
export type InvitationMail={company:string;contact:string;code:string;expires_at:string;language?:Language};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const head=`<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light only"><meta name="supported-color-schemes" content="light"><style>:root{color-scheme:light only!important;supported-color-schemes:light!important}body,.nx-page{background:#fffdf9!important;color:#252724!important}.nx-card{background:#fff!important}.nx-panel{background:#f4ffdf!important;color:#252724!important}.nx-warm{background:#fff0e5!important;color:#4b5643!important}.nx-header{background:#fffdf9!important}.nx-footer{background:#f1f5e9!important}@media(prefers-color-scheme:dark){body,.nx-page{background:#fffdf9!important;color:#252724!important}.nx-card{background:#fff!important}.nx-panel{background:#f4ffdf!important;color:#252724!important}.nx-warm{background:#fff0e5!important;color:#4b5643!important}.nx-header{background:#fffdf9!important}.nx-footer{background:#f1f5e9!important}}</style>`;
export function invitationSubjectFor(language:Language='de'){return language==='en'?'Your sales workflow in one system – your personal neXaro CRM demo':'Dein Vertriebsalltag in einem System – deine persönliche neXaro CRM Demo'}
export const invitationSubject=invitationSubjectFor('de');

export function invitationMail(input:InvitationMail){
 const language:Language=input.language==='en'?'en':'de',english=language==='en';
 const expiry=new Intl.DateTimeFormat(english?'en-GB':'de-DE',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Berlin'}).format(new Date(input.expires_at))+(english?' (Berlin time)':' Uhr (Berlin)');
 const greeting=english?`Hello ${input.contact},`:`Hallo ${input.contact},`;
 const subject=invitationSubjectFor(language);
 const text=english
 ?`${greeting}\n\nyour personal access to the neXaro CRM product demo is ready. The demo shows how leads, customers, appointments, offers and field sales can work together in one continuous sales process.\n\nFor ${input.company}, pay particular attention to where manual steps, information loss or duplicate work occur today – and how a central workflow can reduce them.\n\nYOUR ACCESS\n${demoLink}?lang=en\nInvitation code: ${input.code}\nValid until: ${expiry}\n\nFOCUS ON THREE THINGS\n1. How quickly a lead becomes a concrete next action.\n2. How customer information, appointments and offers come together in one place.\n3. Which workflows can be automated without losing the personal sales approach.\n\nBest regards\nSebastian Pötschke\nneXaro Solutions\nkontakt@nexaro-solutions.de · 0171 9098831`
 :`${greeting}\n\ndein persönlicher Zugang zur neXaro CRM Produktvorführung ist bereit. Die Demo zeigt dir, wie Leads, Kunden, Termine, Angebote und Außendienst in einem durchgängigen Vertriebsprozess zusammenspielen können.\n\nFür ${input.company} kannst du dir besonders ansehen, wo heute manuelle Schritte, Informationsverluste oder unnötige Doppelarbeit entstehen – und wie ein zentraler Ablauf diese Punkte reduziert.\n\nDEIN ZUGANG\n${demoLink}\nEinladungscode: ${input.code}\nGültig bis: ${expiry}\n\nAM BESTEN ACHTEST DU AUF DREI DINGE\n1. Wie schnell du vom Lead zur nächsten konkreten Aktion kommst.\n2. Wie Kundeninformationen, Termine und Angebote an einer Stelle zusammenlaufen.\n3. Welche Abläufe sich automatisieren lassen, ohne dass der persönliche Vertrieb verloren geht.\n\nViele Grüße\nSebastian Pötschke\nneXaro Solutions\nkontakt@nexaro-solutions.de · 0171 9098831`;

 const header=`<tr><td class="nx-header" bgcolor="#fffdf9" style="padding:24px 30px;background:#fffdf9!important;border-top:4px solid #ff6b00;border-bottom:1px solid #e7e0d9;color:#252724!important"><div style="font-size:30px;font-weight:900;letter-spacing:-1.4px;color:#252724!important">ne<span style="color:#ff6b00!important">X</span>aro</div><div style="margin-top:2px;font-size:10px;font-weight:800;color:#59634e!important;letter-spacing:4px">SOLUTIONS</div><div style="height:5px;background:#baff00!important;margin-top:18px;border-radius:5px"></div></td></tr>`;
 const footer=`<tr><td class="nx-footer" bgcolor="#f1f5e9" style="padding:22px 30px;background:#f1f5e9!important;border-top:4px solid #baff00;font-size:11px;line-height:1.65;color:#59634e!important"><strong style="color:#263021!important">neXaro Solutions</strong> · Kirchstraße 1A · 15757 Halbe<br><a href="https://www.nexaro-solutions.de/" style="color:#374a13!important">Website</a> · <a href="https://www.nexaro-solutions.de/impressum.html" style="color:#374a13!important">${english?'Legal notice':'Impressum'}</a> · <a href="https://www.nexaro-solutions.de/datenschutz.html" style="color:#374a13!important">${english?'Privacy':'Datenschutz'}</a></td></tr>`;
 const html=english
 ?`<!doctype html><html lang="en"><head>${head}<title>${esc(subject)}</title></head><body class="nx-page" bgcolor="#fffdf9" style="margin:0;background:#fffdf9!important;color:#252724!important;font-family:Arial,Helvetica,sans-serif;line-height:1.62"><table role="presentation" width="100%" bgcolor="#fffdf9"><tr><td style="padding:26px 12px"><table class="nx-card" role="presentation" width="100%" bgcolor="#ffffff" style="max-width:640px;margin:auto;background:#fff!important;border:1px solid #e7e0d9;border-radius:20px;overflow:hidden">${header}<tr><td style="padding:34px 30px"><p style="margin:0;color:#a44000;font-size:11px;font-weight:800;letter-spacing:1.6px">YOUR PERSONAL CRM DEMO</p><h1 style="font-size:30px;line-height:1.14;color:#252724!important">See how much easier a continuous sales process can be.</h1><p>${esc(greeting)}</p><p>Your personal access for <strong>${esc(input.company)}</strong> is ready. The demo shows how leads, customers, appointments, offers and field sales work together in one process instead of spreading information across different tools and lists.</p><table class="nx-panel" role="presentation" width="100%" bgcolor="#f4ffdf" style="margin:24px 0;background:#f4ffdf!important;border:1px solid #cfe68b;border-left:5px solid #baff00;border-radius:14px"><tr><td style="padding:20px"><strong>Your personal access</strong><p style="font-family:monospace;word-break:break-all;background:#fff!important;padding:12px;border-radius:8px;border:1px solid #d8e4be">${esc(input.code)}</p><p>Valid until <strong>${esc(expiry)}</strong></p><table role="presentation"><tr><td bgcolor="#ff6b00" style="border-radius:10px"><a href="${demoLink}?lang=en" style="display:inline-block;background:#ff6b00!important;color:#172015!important;text-decoration:none;font-weight:800;padding:14px 20px;border-radius:10px">Explore the CRM now →</a></td></tr></table></td></tr></table><h2 style="color:#252724!important">What to focus on in the demo.</h2><p>See how quickly a lead becomes a concrete next action, how customer information, appointments and offers come together in one place, and which recurring steps can be automated.</p><div class="nx-warm" style="margin:24px 0;padding:18px;border-left:5px solid #ff6b00;background:#fff0e5!important;border-radius:0 12px 12px 0"><strong>The key point:</strong><br>A CRM should not create extra work. It should reduce work, create transparency and prevent sales opportunities from being lost between notes, spreadsheets and follow-ups.</div><p>Best regards<br><strong>Sebastian Pötschke</strong><br>neXaro Solutions</p></td></tr>${footer}</table></td></tr></table></body></html>`
 :`<!doctype html><html lang="de"><head>${head}<title>${esc(subject)}</title></head><body class="nx-page" bgcolor="#fffdf9" style="margin:0;background:#fffdf9!important;color:#252724!important;font-family:Arial,Helvetica,sans-serif;line-height:1.62"><table role="presentation" width="100%" bgcolor="#fffdf9"><tr><td style="padding:26px 12px"><table class="nx-card" role="presentation" width="100%" bgcolor="#ffffff" style="max-width:640px;margin:auto;background:#fff!important;border:1px solid #e7e0d9;border-radius:20px;overflow:hidden">${header}<tr><td style="padding:34px 30px"><p style="margin:0;color:#a44000;font-size:11px;font-weight:800;letter-spacing:1.6px">DEINE PERSÖNLICHE CRM-DEMO</p><h1 style="font-size:30px;line-height:1.14;color:#252724!important">Sieh dir an, wie viel einfacher ein durchgängiger Vertriebsprozess sein kann.</h1><p>${esc(greeting)}</p><p>dein persönlicher Zugang für <strong>${esc(input.company)}</strong> ist bereit. Die Demo zeigt dir, wie Leads, Kunden, Termine, Angebote und Außendienst in einem gemeinsamen Prozess zusammenspielen – statt Informationen über mehrere Tools und Listen zu verteilen.</p><table class="nx-panel" role="presentation" width="100%" bgcolor="#f4ffdf" style="margin:24px 0;background:#f4ffdf!important;border:1px solid #cfe68b;border-left:5px solid #baff00;border-radius:14px"><tr><td style="padding:20px"><strong>Dein persönlicher Zugang</strong><p style="font-family:monospace;word-break:break-all;background:#fff!important;padding:12px;border-radius:8px;border:1px solid #d8e4be">${esc(input.code)}</p><p>Gültig bis <strong>${esc(expiry)}</strong></p><table role="presentation"><tr><td bgcolor="#ff6b00" style="border-radius:10px"><a href="${demoLink}" style="display:inline-block;background:#ff6b00!important;color:#172015!important;text-decoration:none;font-weight:800;padding:14px 20px;border-radius:10px">CRM jetzt selbst erleben →</a></td></tr></table></td></tr></table><h2 style="color:#252724!important">Achte in der Demo besonders darauf.</h2><p>Wie schnell aus einem Lead eine konkrete nächste Aktion wird, wie Kundeninformationen, Termine und Angebote an einer Stelle zusammenlaufen und welche wiederkehrenden Schritte sich automatisieren lassen.</p><div class="nx-warm" style="margin:24px 0;padding:18px;border-left:5px solid #ff6b00;background:#fff0e5!important;border-radius:0 12px 12px 0"><strong>Der entscheidende Punkt:</strong><br>Ein CRM sollte nicht zusätzliche Arbeit erzeugen. Es sollte dir Arbeit abnehmen, Transparenz schaffen und dafür sorgen, dass weniger Verkaufschancen zwischen Notizen, Tabellen und Wiedervorlagen verloren gehen.</div><p>Viele Grüße<br><strong>Sebastian Pötschke</strong><br>neXaro Solutions</p></td></tr>${footer}</table></td></tr></table></body></html>`;
 return {subject,text,html};
}
