import {useEffect,useState} from 'react';
import {client} from '../lib/client';
import {useStore} from '../lib/store';
import './software-sales.css';
const labels:Record<string,string>={new:'Neu',contacted:'In Kontakt',demo:'Demo vereinbart',proposal:'Angebot',pilot:'Pilotbetrieb',won:'Gewonnen',lost:'Verloren',archived:'Archiviert'};
type Lead={id?:string;company:string;contact:string;email:string;phone:string;city:string;industry:string;users_count:string;request_kind:string;message:string;status:string;notes:string;next_contact:string|null;created_at?:string;updated_at?:string;source?:string};
type Invitation={id:string;request_id:string|null;label:string;created_at:string;expires_at:string;revoked_at:string|null};
const empty:Lead={company:'',contact:'',email:'',phone:'',city:'',industry:'',users_count:'',request_kind:'consultation',message:'',status:'new',notes:'',next_contact:null};
const date=(s:string)=>new Date(s).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'});
async function api(payload:object){const {data,error}=await client.functions.invoke('nx-software-sales',{body:payload});if(error){let message='Die Anfrage konnte nicht abgeschlossen werden.';try{message=(await error.context.json()).error||message}catch{/* No JSON error body. */}throw Error(message)}if(data?.error)throw Error(data.error);return data}
export function SoftwareSales(){
 const {demo}=useStore();const [rows,setRows]=useState<Lead[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[draft,setDraft]=useState<Lead|null>(null),[dirty,setDirty]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('open'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[days,setDays]=useState(7),[issued,setIssued]=useState<{code:string;invitation:Invitation;recipient:string}|null>(null);
 async function load(){setError('');setBusy('load');try{if(demo){setRows([{...empty,id:'demo',company:'Beispielunternehmen',contact:'Alex Beispiel',email:'demo@example.invalid',industry:'Dienstleistungen',users_count:'5–10',message:'Wir möchten unsere Vertriebsabläufe besser strukturieren.',source:'website',created_at:new Date().toISOString()}]);return}const data=await api({action:'list'});setRows(data.rows);setInvitations(data.invitations);if(data.truncated)setNotice('Es werden die neuesten 1.000 Anfragen und Einladungen angezeigt.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 useEffect(()=>{void load()},[demo]);
 function choose(row:Lead){if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setDraft({...row});setDirty(false);setError('');setNotice('')}
 function patch<K extends keyof Lead>(key:K,value:Lead[K]){setDraft(d=>d?{...d,[key]:value}:d);setDirty(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||demo)return;setBusy('save');setError('');try{const data=await api({action:'save',id:draft.id,updated_at:draft.updated_at,payload:draft});setRows(rs=>[data.row,...rs.filter(r=>r.id!==data.row.id)]);setDraft(data.row);setDirty(false);setNotice('Anfrage gespeichert.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function issue(){if(!draft?.id||dirty||demo)return;setBusy('invite');setError('');try{const data=await api({action:'invite',request_id:draft.id,days});setInvitations(is=>[data.invitation,...is]);setIssued({...data,recipient:draft.email})}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function revoke(inv:Invitation){if(demo||!window.confirm('Einladung für '+inv.label+' jetzt sperren?'))return;setBusy(inv.id);setError('');try{await api({action:'revoke',id:inv.id});setInvitations(is=>is.map(i=>i.id===inv.id?{...i,revoked_at:new Date().toISOString()}:i));if(issued?.invitation.id===inv.id)setIssued(null);setNotice('Einladung gesperrt. Laufende Vorführungen prüfen den Zugang spätestens nach 30 Sekunden erneut.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 const today=new Date().toLocaleDateString('sv-SE');const open=(r:Lead)=>!['won','lost','archived'].includes(r.status);
 const shown=rows.filter(r=>(filter==='all'||filter==='open'&&open(r)||filter==='due'&&open(r)&&r.next_contact&&r.next_contact<=today||r.status===filter)&&[r.company,r.contact,r.email,r.message].join(' ').toLowerCase().includes(search.toLowerCase()));
 const inviteState=(i:Invitation)=>i.revoked_at?'Gesperrt':Date.parse(i.expires_at)<=Date.now()?'Abgelaufen':'Aktiv';
 const inviteList=(items:Invitation[])=><div className="sw-invitations">{items.length?items.map(i=><div className="sw-invitation" key={i.id}><div><strong>{i.label}</strong><small>{inviteState(i)} · gültig bis {date(i.expires_at)}</small></div>{inviteState(i)==='Aktiv'&&<button type="button" disabled={!!busy||demo} onClick={()=>void revoke(i)}>Sperren</button>}</div>):<p>Noch keine Einladungen vorhanden.</p>}</div>;
 const text=issued?`Guten Tag,\n\nentdecken Sie neXaro – über zehn Jahre Vertriebserfahrung in einem individuell anpassbaren Vertriebsprogramm.\n\nIhre persönliche Produktvorführung: https://www.nexaro-solutions.de/produktrundgang/\nEinladungscode: ${issued.code}\nGültig bis: ${date(issued.invitation.expires_at)}\n\nBitte geben Sie den Code nicht weiter.\n\nFreundliche Grüße\nSebastian Pötschke · neXaro Solutions`:'';
 return <section className="software-sales"><div className="section-intro"><div><h1>Software-Vertrieb</h1><p>Unternehmensanfragen, individuelle Projekte und persönliche Demo-Einladungen.</p></div><div className="sw-actions"><button disabled={!!busy} onClick={()=>void load()}>Aktualisieren</button><button className="primary" onClick={()=>choose({...empty})}>Neue Anfrage</button></div></div>
 <div className="sw-metrics"><button onClick={()=>setFilter('new')}><strong>{rows.filter(r=>r.status==='new').length}</strong>Neue Anfragen</button><button onClick={()=>setFilter('open')}><strong>{rows.filter(open).length}</strong>Offene Vorgänge</button><button onClick={()=>setFilter('due')}><strong>{rows.filter(r=>open(r)&&r.next_contact&&r.next_contact<=today).length}</strong>Heute & überfällig</button><button onClick={()=>setFilter('pilot')}><strong>{rows.filter(r=>r.status==='pilot').length}</strong>Pilotbetriebe</button></div>
 {demo&&<p className="sw-hint">Beispielansicht: Es werden keine echten Anfragen geladen oder Einladungscodes erstellt.</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="sw-hint" role="status">{notice}</p>}
 {issued&&<aside className="sw-code" aria-label="Neue Einladung"><h2>Einladung erstellt</h2><strong>{issued.invitation.label}</strong><p>Der Code wird nur jetzt angezeigt. Bitte kopieren, bevor du diese Ansicht schließt. Er wird nicht automatisch versendet.</p><label>Einladungscode<input readOnly value={issued.code} onFocus={e=>e.currentTarget.select()}/></label><small>Gültig bis {date(issued.invitation.expires_at)}</small><details><summary>Einladungstext anzeigen</summary><textarea readOnly value={text} rows={9} onFocus={e=>e.currentTarget.select()}/></details><div className="sw-actions"><button onClick={()=>{if(!navigator.clipboard){setNotice('Bitte den Einladungstext markieren und manuell kopieren.');return}void navigator.clipboard.writeText(text).then(()=>setNotice('Einladungstext kopiert.')).catch(()=>setNotice('Bitte den Einladungstext markieren und manuell kopieren.'))}}>Einladung kopieren</button><a className="primary" href={'mailto:'+encodeURIComponent(issued.recipient)+'?subject='+encodeURIComponent('Ihre persönliche neXaro Produktvorführung')+'&body='+encodeURIComponent(text)}>E-Mail-Entwurf öffnen</a><button onClick={()=>setIssued(null)}>Code-Anzeige schließen</button></div></aside>}
 <div className="sw-grid"><div className="sw-panel"><div className="sw-filters"><label>Suche<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Unternehmen, Name, E-Mail"/></label><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Offene Vorgänge</option><option value="all">Alle</option><option value="due">Heute & überfällig</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><p className="sw-count">{shown.length} Anfragen {busy==='load'?'· wird geladen …':''}</p><div className="sw-list">{shown.map(r=><button className={draft?.id===r.id?'selected':''} key={r.id} onClick={()=>choose(r)}><strong>{r.company}</strong><span>{r.contact} · {labels[r.status]}</span><small>{r.created_at?date(r.created_at):''}{r.next_contact?' · Wiedervorlage '+r.next_contact.split('-').reverse().join('.'):''}</small></button>)}{!shown.length&&busy!=='load'&&<p>Keine passenden Anfragen. Neue Website-Anfragen erscheinen hier nach dem Aktualisieren.</p>}</div></div>
 <div className="sw-panel">{draft?<><h2>{draft.id?'Anfrage bearbeiten':'Neue Anfrage erfassen'}</h2><p className="sw-count">{draft.source==='website'?'Eingang über die Landingpage':draft.id?'Manuell erfasst':'Neuer Vorgang'}{dirty?' · ungespeicherte Änderungen':''}</p><form onSubmit={e=>void save(e)}><div className="sw-fields">{([['company','Unternehmen',200],['contact','Ansprechpartner',160],['email','E-Mail',254],['phone','Telefon',40],['city','Ort',120],['industry','Branche',100],['users_count','Geplante Nutzer',40]] as const).map(([key,label,max])=><label key={key}>{label}<input type={key==='email'?'email':key==='phone'?'tel':'text'} required={['company','contact','email'].includes(key)} maxLength={max} value={draft[key]} onChange={e=>patch(key,e.target.value)}/></label>)}<label>Anliegen<select value={draft.request_kind} onChange={e=>patch('request_kind',e.target.value)}><option value="consultation">Beratung & Anpassung</option><option value="demo">Demo-Einladung</option><option value="pilot">Pilotbetrieb</option></select></label><label>Status<select value={draft.status} onChange={e=>patch('status',e.target.value)}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Wiedervorlage<input type="date" value={draft.next_contact||''} onChange={e=>patch('next_contact',e.target.value||null)}/></label></div><label>Projekt / Nachricht<textarea rows={4} maxLength={3000} value={draft.message} onChange={e=>patch('message',e.target.value)}/></label><label>Interne Notizen & nächster Schritt<textarea rows={4} maxLength={6000} value={draft.notes} onChange={e=>patch('notes',e.target.value)}/></label><button className="primary" disabled={!!busy||demo}>{busy==='save'?'Wird gespeichert …':'Anfrage speichern'}</button></form>
 {draft.id&&<div className="sw-demo-tools"><h3>Persönliche Produktvorführung</h3><p>Die Gültigkeit beginnt beim Erstellen. Bestehende Codes bleiben gültig, bis sie ablaufen oder gesperrt werden.</p><div className="sw-actions"><label>Gültigkeit<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,3,7,14,30].map(d=><option key={d} value={d}>{d} {d===1?'Tag':'Tage'}</option>)}</select></label><button disabled={!!busy||dirty||demo||!!issued} onClick={()=>void issue()}>Einladungscode erstellen</button></div>{dirty&&<small>Bitte die Anfrage zuerst speichern.</small>}{issued&&<small>Bitte zuerst den angezeigten Code sichern und schließen.</small>}{inviteList(invitations.filter(i=>i.request_id===draft.id))}</div>}</>:<div className="sw-empty"><h2>Ein eigener Bereich für dein Softwaregeschäft.</h2><p>Wähle eine Anfrage aus oder lege einen neuen Vorgang an. Du kannst Anforderungen dokumentieren, den nächsten Kontakt planen und Einladungen für die Produktvorführung verwalten.</p><a href="https://www.nexaro-solutions.de/#software" target="_blank" rel="noreferrer">Öffentlichen Produktbereich öffnen ↗</a></div>}</div></div>
 <details className="sw-panel sw-all-invites"><summary>Alle Demo-Einladungen ({invitations.length}) – einschließlich bisheriger Einladungen</summary>{inviteList(invitations)}</details>
 </section>;
}
