import {useEffect,useState} from 'react';
import {client} from '../lib/client';
import {useStore} from '../lib/store';
import {SoftwareInvitation,type PreparedInvitation} from '../components/SoftwareInvitation';
import './software-sales.css';
const labels:Record<string,string>={new:'Neu',contacted:'In Kontakt',demo:'Demo vereinbart',proposal:'Angebot',pilot:'Pilotbetrieb',won:'Gewonnen',lost:'Verloren',archived:'Archiviert'};
type Lead={id?:string;customer_id?:string|null;company:string;contact:string;email:string;phone:string;city:string;industry:string;users_count:string;request_kind:string;message:string;status:string;notes:string;next_contact:string|null;created_at?:string;updated_at?:string;source?:string};
type Delivery={invitation_id:string;recipient:string;status:string;created_at:string;accepted_at:string|null};
type Invitation={id:string;request_id:string|null;label:string;created_at:string;expires_at:string;revoked_at:string|null};
const empty:Lead={company:'',contact:'',email:'',phone:'',city:'',industry:'',users_count:'',request_kind:'consultation',message:'',status:'new',notes:'',next_contact:null};
const date=(s:string)=>new Date(s).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'});
async function api(payload:object){const {data,error}=await client.functions.invoke('nx-software-sales',{body:payload});if(error){let message='Die Anfrage konnte nicht abgeschlossen werden.';try{message=(await error.context.json()).error||message}catch{/* No JSON error body. */}throw Error(message)}if(data?.error)throw Error(data.error);return data}
export function SoftwareSales(){
 const {demo,data:storeData,refresh}=useStore();const [rows,setRows]=useState<Lead[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[customerChoice,setCustomerChoice]=useState(''),[draft,setDraft]=useState<Lead|null>(null),[dirty,setDirty]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('open'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[days,setDays]=useState(7),[issued,setIssued]=useState<PreparedInvitation|null>(null);
 async function load(){setError('');setBusy('load');try{if(demo){setRows([{...empty,id:'demo',company:'Beispielunternehmen',contact:'Alex Beispiel',email:'demo@example.invalid',industry:'Dienstleistungen',users_count:'5–10',message:'Wir möchten unsere Vertriebsabläufe besser strukturieren.',source:'website',created_at:new Date().toISOString()}]);return}const data=await api({action:'list'});setRows(data.rows);setInvitations(data.invitations);setDeliveries(data.deliveries||[]);if(data.truncated)setNotice('Es werden die neuesten 1.000 Anfragen und Einladungen angezeigt.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 useEffect(()=>{void load()},[demo]);
 function choose(row:Lead){if(busy)return;if(dirty&&!window.confirm('Ungespeicherte Änderungen verwerfen?'))return;setDraft({...row});setCustomerChoice('');setDirty(false);setError('');setNotice('')}
 function patch<K extends keyof Lead>(key:K,value:Lead[K]){setDraft(d=>d?{...d,[key]:value}:d);setDirty(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft||demo||busy)return;setBusy('save');setError('');try{const data=await api({action:'save',id:draft.id,updated_at:draft.updated_at,payload:draft});setRows(rs=>[data.row,...rs.filter(r=>r.id!==data.row.id)]);setDraft(data.row);setDirty(false);setNotice(data.row.customer_id?'Anfrage gespeichert und zentral als CRM Software verknüpft.':'Anfrage gespeichert. Bitte die zentrale Kundenakte unten zuordnen.');void refresh()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function issue(){if(!draft?.id||dirty||demo||busy)return;setBusy('invite');setError('');try{const data=await api({action:'invite',request_id:draft.id,days});setInvitations(is=>[data.invitation,...is]);setIssued(data);window.scrollTo({top:0,behavior:'smooth'})}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function linkCustomer(create=false){if(!draft?.id||dirty||demo||busy)return;if(create&&!window.confirm('Eine separate Kundenakte mit dem Vermerk CRM Software anlegen? Bitte zuvor vorhandene Kunden prüfen.'))return;if(customerChoice&&!create&&!window.confirm('Diese Anfrage mit der ausgewählten Kundenakte verknüpfen? Bestehende Stammdaten bleiben unverändert.'))return;setBusy('customer');setError('');try{const result=await api({action:'link_customer',request_id:draft.id,customer_id:create?null:customerChoice||null,create});setDraft(result.row);setRows(rs=>rs.map(r=>r.id===result.row.id?result.row:r));setNotice(result.customer_id?'Zentrale Kundenakte verknüpft · CRM Software.':'Mögliche Dublette gefunden. Bitte eine vorhandene Kundenakte auswählen oder bewusst eine separate anlegen.');void refresh()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function sendInvitation(){if(!issued||demo||busy)throw Error('Bitte warten, bis die aktuelle Aktion beendet ist.');setBusy('send');try{await api({action:'send_invitation',id:issued.invitation.id,code:issued.code,recipient:issued.lead.email,updated_at:issued.lead.updated_at});void refresh()}finally{setBusy('');void load()}}
 async function revoke(inv:Invitation){if(demo||!window.confirm('Einladung für '+inv.label+' jetzt sperren?'))return;setBusy(inv.id);setError('');try{await api({action:'revoke',id:inv.id});setInvitations(is=>is.map(i=>i.id===inv.id?{...i,revoked_at:new Date().toISOString()}:i));if(issued?.invitation.id===inv.id)setIssued(null);setNotice('Einladung gesperrt. Laufende Vorführungen prüfen den Zugang spätestens nach 30 Sekunden erneut.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 const today=new Date().toLocaleDateString('sv-SE');const open=(r:Lead)=>!['won','lost','archived'].includes(r.status);
 const shown=rows.filter(r=>(filter==='all'||filter==='open'&&open(r)||filter==='due'&&open(r)&&r.next_contact&&r.next_contact<=today||r.status===filter)&&[r.company,r.contact,r.email,r.message].join(' ').toLowerCase().includes(search.toLowerCase()));
 const inviteState=(i:Invitation)=>i.revoked_at?'Gesperrt':Date.parse(i.expires_at)<=Date.now()?'Abgelaufen':'Aktiv';
 const inviteList=(items:Invitation[])=><div className="sw-invitations">{items.length?items.map(i=>{const delivery=deliveries.find(d=>d.invitation_id===i.id);return <div className="sw-invitation" key={i.id}><div><strong>{i.label}</strong><small>{inviteState(i)} · gültig bis {date(i.expires_at)}</small><small>{delivery?delivery.status==='accepted'?`✓ Mailserver-Annahme am ${date(delivery.accepted_at||delivery.created_at)} · ${delivery.recipient}`:`Versandstatus unbestätigt · ${delivery.recipient} · bitte Postausgang prüfen; nicht erneut senden`:'Noch kein direkter E-Mail-Versand dokumentiert'}</small></div>{inviteState(i)==='Aktiv'&&<button type="button" disabled={!!busy||demo} onClick={()=>void revoke(i)}>Sperren</button>}</div>}):<p>Noch keine Einladungen vorhanden.</p>}</div>;
 return <section className="software-sales"><div className="section-intro"><div><h1>Software-Vertrieb</h1><p>Unternehmensanfragen, individuelle Projekte und persönliche Demo-Einladungen.</p></div><div className="sw-actions"><button disabled={!!busy} onClick={()=>void load()}>Aktualisieren</button><button className="primary" onClick={()=>choose({...empty})}>Neue Anfrage</button></div></div>
 <div className="sw-metrics"><button onClick={()=>setFilter('new')}><strong>{rows.filter(r=>r.status==='new').length}</strong>Neue Anfragen</button><button onClick={()=>setFilter('open')}><strong>{rows.filter(open).length}</strong>Offene Vorgänge</button><button onClick={()=>setFilter('due')}><strong>{rows.filter(r=>open(r)&&r.next_contact&&r.next_contact<=today).length}</strong>Heute & überfällig</button><button onClick={()=>setFilter('pilot')}><strong>{rows.filter(r=>r.status==='pilot').length}</strong>Pilotbetriebe</button></div>
 {demo&&<p className="sw-hint">Beispielansicht: Es werden keine echten Anfragen geladen oder Einladungscodes erstellt.</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="sw-hint" role="status">{notice}</p>}
 {issued&&<SoftwareInvitation key={issued.invitation.id} issued={issued} onSend={sendInvitation} onClose={()=>setIssued(null)}/>}
 <div className="sw-grid"><div className="sw-panel"><div className="sw-filters"><label>Suche<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Unternehmen, Name, E-Mail"/></label><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Offene Vorgänge</option><option value="all">Alle</option><option value="due">Heute & überfällig</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><p className="sw-count">{shown.length} Anfragen {busy==='load'?'· wird geladen …':''}</p><div className="sw-list">{shown.map(r=><button className={draft?.id===r.id?'selected':''} key={r.id} onClick={()=>choose(r)}><strong>{r.company}</strong><span>{r.contact} · {labels[r.status]}</span><small>{r.created_at?date(r.created_at):''}{r.next_contact?' · Wiedervorlage '+r.next_contact.split('-').reverse().join('.'):''}</small></button>)}{!shown.length&&busy!=='load'&&<p>Keine passenden Anfragen. Neue Website-Anfragen erscheinen hier nach dem Aktualisieren.</p>}</div></div>
 <div className="sw-panel">{draft?<><h2>{draft.id?'Anfrage bearbeiten':'Neue Anfrage erfassen'}</h2><p className="sw-count">{draft.source==='website'?'Eingang über die Landingpage':draft.id?'Manuell erfasst':'Neuer Vorgang'}{dirty?' · ungespeicherte Änderungen':''}</p><form onSubmit={e=>void save(e)}><div className="sw-fields">{([['company','Unternehmen',200],['contact','Ansprechpartner',160],['email','E-Mail',254],['phone','Telefon',40],['city','Ort',120],['industry','Branche',100],['users_count','Geplante Nutzer',40]] as const).map(([key,label,max])=><label key={key}>{label}<input type={key==='email'?'email':key==='phone'?'tel':'text'} required={['company','contact','email'].includes(key)} maxLength={max} value={draft[key]} onChange={e=>patch(key,e.target.value)}/></label>)}<label>Anliegen<select value={draft.request_kind} onChange={e=>patch('request_kind',e.target.value)}><option value="consultation">Beratung & Anpassung</option><option value="demo">Demo-Einladung</option><option value="pilot">Pilotbetrieb</option></select></label><label>Status<select value={draft.status} onChange={e=>patch('status',e.target.value)}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Wiedervorlage<input type="date" value={draft.next_contact||''} onChange={e=>patch('next_contact',e.target.value||null)}/></label></div><label>Projekt / Nachricht<textarea rows={4} maxLength={3000} value={draft.message} onChange={e=>patch('message',e.target.value)}/></label><label>Interne Notizen & nächster Schritt<textarea rows={4} maxLength={6000} value={draft.notes} onChange={e=>patch('notes',e.target.value)}/></label><button className="primary" disabled={!!busy||demo}>{busy==='save'?'Wird gespeichert …':'Anfrage speichern'}</button></form>
 {draft.id&&<section className="sw-customer-link" aria-label="Zentrale Kundenakte"><span className="sw-badge">CRM Software</span><h3>{draft.customer_id?'Zentral erfasst & verknüpft':'Kundenakte zuordnen'}</h3>{draft.customer_id?<><p>{storeData.customers.find(c=>c.id===draft.customer_id)?.company||draft.company} · Bestehende Stammdaten bleiben unverändert. Änderungen der Anfrage werden nicht ungeprüft in die Kundenakte übernommen.</p><a href={'?nx=inquiry&customer='+encodeURIComponent(draft.customer_id)}>Zentrale Kundenakte öffnen →</a></>:<><p>Neue Anfragen werden automatisch zentral angelegt. Bei möglichen Dubletten bitte die richtige Akte auswählen.</p><label>Vorhandene Kundenakte<select disabled={!!busy||demo} value={customerChoice} onChange={e=>setCustomerChoice(e.target.value)}><option value="">Automatische Prüfung</option>{storeData.customers.map(c=><option key={c.id} value={c.id}>{c.company} · {c.email||c.contact||c.city}</option>)}</select></label><div className="sw-actions"><button disabled={!!busy||dirty||demo} onClick={()=>void linkCustomer()}>{customerChoice?'Ausgewählte Akte verknüpfen':'Kundenzuordnung prüfen'}</button><button disabled={!!busy||dirty||demo} onClick={()=>void linkCustomer(true)}>Separate Kundenakte anlegen</button></div></>}</section>}
 {draft.id&&<div className="sw-demo-tools"><h3>Persönliche Produktvorführung</h3><p>1. Gültigkeit wählen · 2. E-Mail prüfen · 3. Einladung senden. Die Gültigkeit beginnt beim Erstellen. Bestehende Codes bleiben bis zum Ablauf oder Sperren gültig.</p><div className="sw-actions"><label>Gültigkeit<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,3,7,14,30].map(d=><option key={d} value={d}>{d} {d===1?'Tag':'Tage'}</option>)}</select></label><button className="primary" disabled={!!busy||dirty||demo||!!issued||!draft.customer_id} onClick={()=>void issue()}>Einladung & E-Mail vorbereiten</button></div>{dirty&&<small>Bitte die Anfrage zuerst speichern.</small>}{!draft.customer_id&&<small>Bitte zuerst die zentrale Kundenakte zuordnen.</small>}{issued&&<small>Die vorbereitete Einladung findest du oben. Bitte zuerst senden oder die Vorschau schließen.</small>}{inviteList(invitations.filter(i=>i.request_id===draft.id))}</div>}</>:<div className="sw-empty"><h2>Ein eigener Bereich für dein Softwaregeschäft.</h2><p>Wähle eine Anfrage aus oder lege einen neuen Vorgang an. Du kannst Anforderungen dokumentieren, den nächsten Kontakt planen und Einladungen für die Produktvorführung verwalten.</p><a href="https://www.nexaro-solutions.de/#software" target="_blank" rel="noreferrer">Öffentlichen Produktbereich öffnen ↗</a></div>}</div></div>
 <details className="sw-panel sw-all-invites"><summary>Alle Demo-Einladungen ({invitations.length}) – einschließlich bisheriger Einladungen</summary>{inviteList(invitations)}</details>
 </section>;
}
