import { createClient } from "npm:@supabase/supabase-js@2.116.0";
const url=Deno.env.get("SUPABASE_URL")||"";
const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers:{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"authorization,apikey,content-type","access-control-allow-methods":"POST,OPTIONS"}});
const html=(s:string,status=200)=>new Response(s,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","referrer-policy":"no-referrer","content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"}});
const escape=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const digest=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,"0")).join("");
const berlin=(d:Date,opts:Intl.DateTimeFormatOptions,language="de")=>new Intl.DateTimeFormat(language==="en"?"en-GB":"de-DE",{timeZone:"Europe/Berlin",...opts}).format(d);
const berlinDay=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
function page(body:string,language="de",status=200){const en=language==="en";return html(`<!doctype html><html lang="${en?"en":"de"}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#202421"><title>${en?"Appointment":"Termin"} | neXaro Solutions</title><style>:root{--orange:#ff6b00;--lime:#baff00;--ink:#252724;--deep:#202421;--warm:#fffdf9;--line:#e7e0d9;--muted:#66665f}*{box-sizing:border-box}body{font:16px/1.6 system-ui,-apple-system,Segoe UI,sans-serif;background:radial-gradient(ellipse at 90% 5%,#ff6b0018,transparent 36%),radial-gradient(ellipse at 5% 30%,#baff001c,transparent 38%),var(--warm);color:var(--ink);margin:0;min-height:100vh;padding:24px}.shell{max-width:620px;margin:5vh auto}.brand{background:var(--deep);border-bottom:5px solid var(--lime);border-radius:20px 20px 0 0;padding:24px 28px;color:#fff}.brand b{font-size:29px;color:var(--orange);letter-spacing:-1px}.brand span{font-size:29px;font-weight:900}.brand small{display:block;color:#d8ddd6;letter-spacing:2px;font-size:9px;margin-top:3px}.card{background:#fff;border:1px solid var(--line);border-top:0;border-radius:0 0 20px 20px;padding:30px 28px;box-shadow:0 18px 50px #25272412}.eyebrow{color:#a84200;font-size:11px;font-weight:850;letter-spacing:1.5px}.card h1{font-size:30px;line-height:1.12;letter-spacing:-1px;margin:8px 0 20px}.card h2{font-size:20px;margin-top:28px}.info{background:#f1ffd5;border:1px solid #cde88c;border-radius:14px;padding:18px 20px;margin:20px 0}.ok{background:#f1ffd5;border-left:5px solid var(--lime);padding:15px 17px;border-radius:0 12px 12px 0}.warn{background:#fff7ef;border-left:5px solid var(--orange);padding:15px 17px;border-radius:0 12px 12px 0}button{background:var(--orange);color:var(--deep);border:0;border-radius:10px;padding:14px 18px;font-size:16px;font-weight:800;cursor:pointer;margin:5px 0;box-shadow:0 8px 22px #ff6b0027}input,textarea{width:100%;padding:13px;margin:7px 0;border:1px solid #d9d1c8;border-radius:10px;font:inherit;background:#fffdf9}input:focus,textarea:focus{outline:3px solid #ff6b0024;border-color:#ff6b00}label{display:block;margin-top:12px;font-weight:700}hr{border:0;border-top:1px solid var(--line);margin:27px 0}.foot{font-size:11px;color:#777b74;margin-top:18px}@media(max-width:560px){body{padding:14px}.shell{margin:2vh auto}.brand{padding:20px}.brand b,.brand span{font-size:25px}.card{padding:25px 20px}.card h1{font-size:27px}}</style></head><body><div class="shell"><header class="brand"><b>neXaro</b> <span>Solutions</span><small>PEOPLE · PAYMENT · PRODUCTS · PROGRESS</small></header><main class="card"><div class="eyebrow">${en?"APPOINTMENT · SERVICE":"TERMIN · SERVICE"}</div><h1>${en?"Your appointment with neXaro.":"Ihr Termin bei neXaro."}</h1>${body}<div class="foot">neXaro Solutions · Kirchstraße 1A · 15757 Halbe</div></main></div></body></html>`,status)}
async function owner(req:Request){const bearer=req.headers.get("authorization")||"";if(!bearer.startsWith("Bearer "))return false;const auth=createClient(url,Deno.env.get("SUPABASE_ANON_KEY")||"",{auth:{persistSession:false}});const {data,error}=await auth.auth.getUser(bearer.slice(7));if(error||!data.user)return false;const result=await db.from("nx_owner").select("user_id").eq("user_id",data.user.id).maybeSingle();return !!result.data&&!result.error;}
async function publicAction(req:Request){
 const u=new URL(req.url),form=req.method==="POST"?await req.formData():null,token=String(form?.get("token")||u.searchParams.get("token")||"");if(!/^[a-f0-9]{64}$/.test(token))return page('<div class="warn">Invalid link.</div>',"en");
 const hash=await digest(token);const {data:record}=await db.from("nx_sms_appointments").select("task_id,status,scheduled_due_at,language").eq("token_hash",hash).maybeSingle();const language=record?.language==="en"?"en":"de",en=language==="en";
 const t=(de:string,enText:string)=>en?enText:de;
 if(!record)return page('<div class="warn">'+t("Dieser Terminlink ist nicht mehr gültig. Bitte kontaktieren Sie neXaro Solutions.","This appointment link is no longer valid. Please contact neXaro Solutions.")+'</div>',language);
 const {data:task}=await db.from("nx_tasks").select("id,title,due_at,kind,done").eq("id",record.task_id).maybeSingle();if(!task||task.kind!=="Termin"||task.done||task.due_at!==record.scheduled_due_at)return page('<div class="warn">'+t("Dieser Termin wurde inzwischen geändert oder abgesagt. Bitte kontaktieren Sie neXaro Solutions.","This appointment has since been changed or cancelled. Please contact neXaro Solutions.")+'</div>',language);
 const info='<div class="info"><strong>'+escape(task.title)+'</strong><br>'+escape(berlin(new Date(task.due_at),{weekday:"long",day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"},language))+(en?" (Berlin time)":" Uhr")+'</div>';
 if(req.method!=="POST"){
  if(record.status==="confirmed")return page(info+'<div class="ok"><strong>✓ '+t("Termin bestätigt","Appointment confirmed")+'</strong><br>'+t("Vielen Dank. Ihre Bestätigung wurde gespeichert.","Thank you. Your confirmation has been saved.")+'</div>',language);
  if(record.status==="reschedule_requested")return page(info+'<div class="ok">'+t("Ihr Verschiebungswunsch wurde übermittelt. Der neue Termin ist erst nach Rückbestätigung durch neXaro verbindlich.","Your rescheduling request has been submitted. The new appointment is only confirmed after neXaro confirms it.")+'</div>',language);
  if(record.status!=="sent")return page('<div class="warn">'+t("Dieser Terminlink ist nicht aktiv.","This appointment link is not active.")+'</div>',language);
  return page(info+'<form method="post"><input type="hidden" name="token" value="'+token+'"><button name="action" value="confirm">✓ '+t("Termin bestätigen","Confirm appointment")+'</button></form><hr><h2>'+t("Termin verschieben","Reschedule appointment")+'</h2><p>'+t("Schlagen Sie ein neues Datum und eine Uhrzeit vor. Der bisherige Termin bleibt bestehen, bis wir Ihnen den neuen Termin bestätigen.","Suggest a new date and time. The existing appointment remains in place until we confirm the new one.")+'</p><form method="post"><input type="hidden" name="token" value="'+token+'"><label>'+t("Wunschtermin (Datum)","Preferred date")+'<input name="day" type="date" required></label><label>'+t("Uhrzeit","Time")+'<input name="time" type="time" required></label><label>'+t("Bemerkung (optional)","Note (optional)")+'<textarea name="note" maxlength="300"></textarea></label><button name="action" value="reschedule">'+t("Verschiebung anfragen","Request rescheduling")+'</button></form>',language);
 }
 if(record.status!=="sent")return page(info+'<div class="warn">'+t("Ihre Rückmeldung wurde bereits erfasst oder der Link ist nicht mehr aktiv.","Your response has already been recorded or the link is no longer active.")+'</div>',language);
 const action=String(form?.get("action")||"");
 if(action==="confirm"){const {data,error}=await db.from("nx_sms_appointments").update({status:"confirmed",confirmed_at:new Date().toISOString()}).eq("task_id",task.id).eq("status","sent").eq("token_hash",hash).select("task_id");return page(info+(error||!data?.length?'<div class="warn">'+t("Die Bestätigung konnte nicht gespeichert werden. Bitte erneut versuchen.","The confirmation could not be saved. Please try again.")+'</div>':'<div class="ok"><strong>✓ '+t("Vielen Dank!","Thank you!")+'</strong><br>'+t("Ihr Termin ist bestätigt.","Your appointment is confirmed.")+'</div>'),language);}
 if(action==="reschedule"){const day=String(form?.get("day")||""),time=String(form?.get("time")||""),note=String(form?.get("note")||"").trim().slice(0,300);if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!/^\d{2}:\d{2}$/.test(time)||day<berlinDay(new Date()))return page(info+'<div class="warn">'+t("Bitte geben Sie einen gültigen zukünftigen Wunschtermin an.","Please enter a valid future preferred appointment.")+'</div>',language,400);const msg=(en?"Preferred appointment: ":"Wunschtermin: ")+day+" "+time+(en?"":" Uhr")+(note?" · "+note:"");const {data,error}=await db.from("nx_sms_appointments").update({status:"reschedule_requested",requested_at:new Date().toISOString(),request_note:msg}).eq("task_id",task.id).eq("status","sent").eq("token_hash",hash).select("task_id");return page(info+(error||!data?.length?'<div class="warn">'+t("Die Anfrage konnte nicht gespeichert werden. Bitte erneut versuchen.","The request could not be saved. Please try again.")+'</div>':'<div class="ok">'+t("Ihr Verschiebungswunsch wurde übermittelt. Der neue Termin ist erst nach Rückbestätigung durch neXaro verbindlich.","Your rescheduling request has been submitted. The new appointment is only confirmed after neXaro confirms it.")+'</div>'),language);}
 return page('<div class="warn">'+t("Unbekannte Aktion.","Unknown action.")+'</div>',language,400);
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return json({});try{const u=new URL(req.url);if(req.method==="GET"||(req.method==="POST"&&(req.headers.get("content-type")||"").includes("application/x-www-form-urlencoded")))return await publicAction(req);if(req.method!=="POST")return json({error:"Method not allowed"},405);const body=await req.json().catch(()=>({}));if(body.action==="dispatch")return json({enabled:false,reason:"SMS permanently disabled: switched to email confirmations"},410);if(!(await owner(req)))return json({error:"Unauthorized"},401);return json({ready:true,enabled:false,message:"Legacy appointment link handler only; email dispatch uses nx-email-appointments"});}catch(e){return json({error:String(e)},500)}});
