import {useState} from "react";
import {sumupSidekickHardware,sumupSidekickLicenses,sidekickHardwareNet,sidekickLicenseMonthly,chooseSidekickLicense,normalizeSidekickSelection,type SumupSidekickSelection} from "../lib/sumup-sidekick";
import "../sidekick-matrix.css";
type Props={value:SumupSidekickSelection;onChange:(s:SumupSidekickSelection)=>void;noFixedTerm?:boolean;};
const icons:Record<string,string>={tap:"📲",lite:"💳",solo:"💳",terminal:"📱",drawer:"🗃️",mpop:"🧾",epson:"🖨️",scanner:"▥",lan:"🔌",soloprinter:"🧾",solodock:"⚡",pos:"🏪",posprinter:"🏪",posdual:"🏪",posbundle:"🏪",kdsdevice:"🍽️"};
const money=(x:number)=>x.toLocaleString("de-DE",{style:"currency",currency:"EUR"});
export function SidekickMatrix({value,onChange,noFixedTerm=false}:Props){
 const [all,setAll]=useState(false);
 const update=(patch:Partial<SumupSidekickSelection>)=>onChange({...value,...patch});
 const qty=(id:string,count:number)=>update({hardware:[...value.hardware.filter(p=>p.id!==id),...(count>0?[{id,quantity:Math.min(20,count)}]:[])]});
 const license=(id:string)=>{if(!noFixedTerm)onChange(chooseSidekickLicense(value,id));};
 const safe=normalizeSidekickSelection(value);
 const total=sidekickHardwareNet(safe),monthly=sidekickLicenseMonthly(safe);
 return <section className="nxside" aria-label="SumUp Sidekick Angebotsmatrix">
  <header className="nxside-hero"><span className="eyebrow">NEXARO · SUMUP ANGEBOTSMATRIX</span><h3>Das passende Angebot zusammenstellen</h3><p>Dein mobiler Beratungsablauf mit offiziellen Referenzpreisen ohne Aktionen. Für SumUp und Vape bleibt die Kundenakte zentral.</p></header>
  <h4>1 · Angebotstyp</h4><div className="nxside-grid">{([["carry","🧳","Carry & Sell","Hardware persönlich übergeben."],["order","📦","Order & Sell","Hardware und Abonnements zusammenstellen."]] as const).map(([id,icon,name,detail])=><button key={id} type="button" className={"nxside-choice "+(value.offerType===id?"selected":"")} onClick={()=>update({offerType:id})}><span className="nxside-icon">{icon}</span><strong>{name}</strong><small>{detail}</small></button>)}</div>
  <h4>2 · Hardware & Zubehör</h4><p className="hint">Produktillustrationen sind schematisch. Bundle-Komponenten nicht zusätzlich doppelt hinzufügen.</p>
  <div className="nxside-grid">{sumupSidekickHardware.filter(p=>all||p.group!=="accessory").map(p=>{const num=value.hardware.find(x=>x.id===p.id)?.quantity||0;return <article className={"nxside-choice "+(num?"selected":"")} key={p.id}><div className="nxside-picture"><img src={"./product-illustrations/"+p.illustration+".svg"} alt={"Schematische Illustration: "+p.name} loading="lazy"/><span aria-hidden="true">{icons[p.id]||"📦"}</span></div><strong>{p.name}</strong><small>{p.description}</small><b>{money(p.price)} netto</b><div className="nxside-actions"><button type="button" className="secondary" onClick={()=>qty(p.id,num?0:1)}>{num?"Entfernen":"Hinzufügen"}</button>{num>0&&<span><button type="button" onClick={()=>qty(p.id,num-1)} aria-label={p.name+" reduzieren"}>−</button>{num}<button type="button" onClick={()=>qty(p.id,num+1)} aria-label={p.name+" erhöhen"}>+</button></span>}</div></article>})}</div>
  <button className="secondary" type="button" onClick={()=>setAll(!all)}>{all?"Weniger anzeigen":"Alle Zubehörartikel anzeigen"}</button>
  <label className="nxside-field">Hardware-Nachlass: {value.discount} %<input type="range" min="0" max="25" step="1" value={value.discount} onChange={e=>update({discount:Number(e.target.value)})}/></label>
  <h4>3 · Genau eine Plus-Variante wählen</h4><p className="hint">Kassensystem Plus, Kassensystem Plus jährlich, Zahlungen Plus und Beauty Plus sind alternativ. Ein Wechsel ersetzt die bisherige Plus-Variante; KDS bleibt nur bei passendem Funktionsbedarf eine Zusatzoption.</p>{noFixedTerm&&<p className="nxside-prefill" role="status">Ohne Laufzeitvertrag: Umsatzbasiertes Zahlen · 1,39 % pro Kartentransaktion · 0,00 € monatliche Tarifgrundgebühr. Die Plus-Lizenzen sind nicht auswählbar.</p>}<div className="nxside-grid">{sumupSidekickLicenses.map(p=><button type="button" disabled={noFixedTerm} className={"nxside-choice "+(safe.licenses.includes(p.id)?"selected":"")} onClick={()=>license(p.id)} key={p.id}><span className="nxside-icon">🧩</span><strong>{p.name}</strong><small>{p.description}</small><b>{money(p.price)} / {p.period==="annual"?"Jahr":"Monat"}</b><span>{value.licenses.includes(p.id)?"✓ Ausgewählt":"+ Auswählen"}</span></button>)}</div>
  <div className="nxside-summary"><h4>🧾 Angebotsübersicht</h4><p>Hardware einmalig netto: <b>{money(total)}</b></p><p>Gewählte Software / Monat (Jahreslizenzen rechnerisch umgelegt): <b>{money(monthly)}</b></p>{noFixedTerm&&<p>Umsatzbasiertes Zahlen · 1,39 % je Kartentransaktion · <b>0,00 € Tarifgrundgebühr / Monat</b></p>}<small>Gesamtkosten und Kartenmix stehen unten im Vergleichsangebot. Hardware und individuelle Konditionen vor verbindlichem Versand prüfen.</small></div>
 </section>;
}
